import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const port=33128;
const backend=path.resolve(import.meta.dirname,'..');
const project=path.resolve(backend,'..');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'arachne-part15-'));
const sqlite=path.join(tmp,'test.sqlite');
const frontendScript=fs.readFileSync(path.join(project,'frontend/script.js'),'utf8');
let server;

async function waitForServer(){const deadline=Date.now()+10000;while(Date.now()<deadline){try{const r=await fetch(`http://127.0.0.1:${port}/api/health`);if(r.ok)return;}catch{}await new Promise(r=>setTimeout(r,60));}throw new Error('Servidor da Parte 15 não iniciou.');}
async function api(route,{method='GET',token,body,clientId='part15-api'}={}){const headers={'Content-Type':'application/json','X-Arachne-Client':clientId};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(`http://127.0.0.1:${port}/api${route}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});let data;try{data=await response.json();}catch{data=null;}return{status:response.status,data};}
async function join(role,heroId=''){const body=role==='master'?{role,campaignCode:'ARACHNE',password:'TESTMASTER'}:{role,campaignCode:'ARACHNE',heroId};const r=await api('/session/join',{method:'POST',body});assert.equal(r.status,200,JSON.stringify(r.data));return r.data.token;}
async function openSse(token,clientId){const controller=new AbortController(),response=await fetch(`http://127.0.0.1:${port}/api/events?token=${encodeURIComponent(token)}&clientId=${encodeURIComponent(clientId)}`,{signal:controller.signal});assert.equal(response.status,200);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',closed=false;const events=[],waiters=[];function deliver(item){events.push(item);for(const waiter of [...waiters])if(waiter.predicate(item)){waiters.splice(waiters.indexOf(waiter),1);clearTimeout(waiter.timer);waiter.resolve(item);}};(async()=>{try{while(!closed){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let i;while((i=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,i);buffer=buffer.slice(i+2);let event='message',raw='';for(const line of block.split('\n')){if(line.startsWith('event:'))event=line.slice(6).trim();if(line.startsWith('data:'))raw+=line.slice(5).trim();}if(!raw)continue;let data;try{data=JSON.parse(raw);}catch{data=raw;}deliver({event,data});}}}catch(error){if(!closed&&error?.name!=='AbortError')throw error;}})();return{waitFor(predicate,timeout=3000){const found=events.find(predicate);if(found)return Promise.resolve(found);return new Promise((resolve,reject)=>{const waiter={predicate,resolve,timer:setTimeout(()=>{const idx=waiters.indexOf(waiter);if(idx>=0)waiters.splice(idx,1);reject(new Error('Timeout SSE Parte 15'));},timeout)};waiters.push(waiter);});},close(){closed=true;controller.abort();reader.cancel().catch(()=>{});}};}
function piecesFor(scenario,id){return (scenario?.pieces||[]).filter(piece=>String(piece?.characterId||piece?.baseId||'')===id);}

async function addMany(master,baseId,count){const out=[];for(let i=0;i<count;i++){const r=await api('/initiative/participants',{method:'POST',token:master,body:{baseId}});assert.equal(r.status,201,JSON.stringify(r.data));out.push(r.data.data);}return out;}

async function rollAll(master,participants){for(const p of participants){const r=await api('/initiative/roll',{method:'POST',token:master,body:{participantId:p.id}});assert.equal(r.status,200,JSON.stringify(r.data));}}

test.before(async()=>{server=spawn(process.execPath,['src/server.js'],{cwd:backend,env:{...process.env,PORT:String(port),DB_PROVIDER:'sqlite',SQLITE_FILE:sqlite,MASTER_PASSWORD:'TESTMASTER',SESSION_SECRET:'test-secret-test-secret-test-secret',SERVE_FRONTEND:'false'},stdio:['ignore','pipe','pipe']});let err='';server.stderr.on('data',d=>{err+=String(d);});server.on('exit',code=>{if(code&&code!==0)console.error(err);});await waitForServer();});
test.after(async()=>{if(server&&!server.killed){server.kill('SIGTERM');await new Promise(r=>setTimeout(r,100));}fs.rmSync(tmp,{recursive:true,force:true});});

test('Capangas podem ser adicionados várias vezes e cada instância recebe token próprio',async()=>{const master=await join('master');const added=await addMany(master,'minion-melee',3);const last=added.at(-1),participants=last.initiative.filter(p=>p.baseId==='minion-melee');assert.equal(participants.length,3);assert.deepEqual(participants.map(p=>p.instanceNumber),[1,2,3]);assert.equal(new Set(participants.map(p=>p.id)).size,3);assert.equal(new Set(participants.map(p=>p.name)).size,3);const pieces=piecesFor(last.scenario,'minion-melee');assert.equal(pieces.length,3);assert.equal(new Set(pieces.map(p=>p.id)).size,3);assert.equal(new Set(pieces.map(p=>p.initiativeParticipantId)).size,3);assert.ok(pieces.every(p=>p.spawnedByInitiative===true&&p.characterId==='minion-melee'));});

test('Agentes da Hydra e I.M.A. são LACAIOS repetíveis e aparecem no grid por instância',async()=>{const master=await join('master');const hydra=await addMany(master,'hydra-agent',3),aim=await addMany(master,'aim-agent',2);const state=await api('/state',{token:master});assert.equal(state.status,200);assert.equal(state.data.data.initiative.filter(p=>p.baseId==='hydra-agent').length,3);assert.equal(state.data.data.initiative.filter(p=>p.baseId==='aim-agent').length,2);assert.equal(piecesFor(state.data.data.scenario,'hydra-agent').length,3);assert.equal(piecesFor(state.data.data.scenario,'aim-agent').length,2);assert.ok(state.data.data.initiative.filter(p=>p.baseId==='hydra-agent').every(p=>p.repeatable===true));assert.ok(state.data.data.initiative.filter(p=>p.baseId==='aim-agent').every(p=>p.repeatable===true));assert.match(hydra[0].participant.name,/Agente da Hydra 1/);assert.match(aim[1].participant.name,/Agente da I\.M\.A\. 2/);});

test('personagem único continua bloqueando duplicação',async()=>{const master=await join('master');const first=await api('/initiative/participants',{method:'POST',token:master,body:{baseId:'octopus'}});assert.equal(first.status,201);const duplicate=await api('/initiative/participants',{method:'POST',token:master,body:{baseId:'octopus'}});assert.equal(duplicate.status,409);assert.match(duplicate.data.error,/Já está na iniciativa/);});

test('remover uma instância genérica remove somente seu token e permite nova instância',async()=>{const master=await join('master');let state=await api('/state',{token:master});const hydras=state.data.data.initiative.filter(p=>p.baseId==='hydra-agent');assert.equal(hydras.length,3);const target=hydras[1];const removed=await api(`/initiative/participants/${encodeURIComponent(target.id)}`,{method:'DELETE',token:master});assert.equal(removed.status,200,JSON.stringify(removed.data));assert.equal(removed.data.data.initiative.filter(p=>p.baseId==='hydra-agent').length,2);assert.equal(piecesFor(removed.data.data.scenario,'hydra-agent').length,2);assert.ok(!removed.data.data.scenario.pieces.some(p=>p.initiativeParticipantId===target.id));const again=await api('/initiative/participants',{method:'POST',token:master,body:{baseId:'hydra-agent'}});assert.equal(again.status,201);assert.equal(again.data.data.initiative.filter(p=>p.baseId==='hydra-agent').length,3);assert.equal(piecesFor(again.data.data.scenario,'hydra-agent').length,3);});

test('múltiplas instâncias genéricas podem rolar iniciativa e iniciar o mesmo combate',async()=>{const master=await join('master');const state=await api('/state',{token:master});const generics=state.data.data.initiative.filter(p=>['minion-melee','hydra-agent','aim-agent'].includes(p.baseId));assert.ok(generics.length>=8);await rollAll(master,generics.filter(p=>p.result===null||p.result===''));const started=await api('/combat/start',{method:'POST',token:master,body:{}});assert.equal(started.status,200,JSON.stringify(started.data));assert.equal(started.data.data.order.filter(p=>p.baseId==='minion-melee').length,3);assert.equal(started.data.data.order.filter(p=>p.baseId==='hydra-agent').length,3);assert.equal(started.data.data.order.filter(p=>p.baseId==='aim-agent').length,2);assert.equal(new Set(started.data.data.order.map(p=>p.id)).size,started.data.data.order.length);});

test('SSE entrega ao jogador todas as instâncias e seus tokens automaticamente',async()=>{const master=await join('master'),player=await join('player','spider'),stream=await openSse(player,'part15-player');await stream.waitFor(e=>e.event==='ready');try{const before=await api('/state',{token:master});const count=before.data.data.initiative.filter(p=>p.baseId==='minion-ranged').length;const addPromise=stream.waitFor(e=>e.event==='state'&&e.data?.key==='scenario'&&piecesFor(e.data.value,'minion-ranged').length===count+1);const added=await api('/initiative/participants',{method:'POST',token:master,body:{baseId:'minion-ranged'}});assert.equal(added.status,201);const pushed=await addPromise;assert.equal(piecesFor(pushed.data.value,'minion-ranged').length,count+1);}finally{stream.close();}});


test('limpar a iniciativa remove tokens automáticos e uma nova preparação começa sem duplicação',async()=>{const master=await join('master');await api('/combat/end',{method:'POST',token:master,body:{}});const cleared=await api('/initiative/participants',{method:'DELETE',token:master});assert.equal(cleared.status,200,JSON.stringify(cleared.data));assert.deepEqual(cleared.data.data.initiative,[]);assert.equal((cleared.data.data.scenario.pieces||[]).filter(p=>p.spawnedByInitiative===true).length,0);const first=await api('/initiative/participants',{method:'POST',token:master,body:{baseId:'hydra-agent'}});assert.equal(first.status,201);assert.equal(first.data.data.initiative.filter(p=>p.baseId==='hydra-agent').length,1);assert.equal(piecesFor(first.data.data.scenario,'hydra-agent').length,1);});

test('frontend libera repetição apenas na preparação e mantém uma única integração iniciativa→grid',()=>{assert.match(frontendScript,/isRepeatableInitiativeEntity/);assert.match(frontendScript,/LACAIO/);assert.match(frontendScript,/PODE REPETIR/);assert.match(frontendScript,/Capangas e ameaças LACAIO podem ser adicionados várias vezes/);assert.equal((frontendScript.match(/function renderScenario\(\)/g)||[]).length,1);assert.equal((frontendScript.match(/function addInitiativeParticipant\(/g)||[]).length,1);});
