const baseAbilities = { Melee:0, Agility:0, Resilience:0, Vigilance:0, Ego:0, Logic:0 };
const clone = value => JSON.parse(JSON.stringify(value));
const session = (id, title, text) => ({ id:String(id).padStart(2,'0'), title, text });

function hero(id,n,r,rank=4,extra={}){
  return {
    id,n,r,rank,tier:'HERÓI',pdf:'',image:'',role:'Herói da campanha',hook:'',
    maxHealth:90,maxFocus:90,currentHealth:90,currentFocus:90,karma:4,healthDR:'—',focusDR:'—',initiative:'+0',
    speed:'Correr 5 · Escalar 3 · Nadar 3 · Pular 3',movement:{run:5,climb:3,swim:3,jump:3},occupation:'',origin:'',teams:'',base:'',
    stats:[['Health',90],['Focus',90],['Karma',4]],abilities:{...baseAbilities},traits:[],tags:['Heroic'],powers:[],
    ...extra
  };
}
function villain(id,n,r='',rank=4,tier='AMEAÇA',extra={}){
  return {
    id,n,r,rank,tier,pdf:'',image:'',role:tier==='CHEFE FINAL'?'VILÃO FINAL':'AMEAÇA',hook:'',
    maxHealth:90,maxFocus:60,currentHealth:90,currentFocus:60,karma:'—',healthDR:'—',focusDR:'—',initiative:'+0',
    speed:'Correr 5 · Escalar 3 · Nadar 3 · Pular 3',movement:{run:5,climb:3,swim:3,jump:3},occupation:'',origin:'',teams:'',base:'',
    abilities:{...baseAbilities},traits:[],tags:['Villainous'],powers:[],
    ...extra
  };
}

const CHARACTER_LIBRARY = {
  heroes: {
    spider: hero('spider','Homem-Aranha','Peter Parker',4,{image:'assets/portraits/hero-spider.jpg',pdf:'assets/pdfs/hero-homem-aranha.pdf',role:'Investigador / mobilidade',hook:'Rastreia roubos tecnológicos e pistas da conspiração.',maxHealth:90,maxFocus:90,currentHealth:90,currentFocus:90,karma:4,initiative:'+3E',speed:'Correr 6 · Escalar 6 · Nadar 3 · Pular 6 · Planar 12 · Balanço com teia 18',movement:{run:6,climb:6,swim:3,jump:6,glide:12,swingline:18},occupation:'Fotógrafo / estudante',origin:'Humano alterado',teams:'Avengers, Fantastic Four, Web-Warriors',base:'Nova York',stats:[['Health',90],['Focus',90],['Karma',4]],abilities:{Melee:5,Agility:7,Resilience:3,Vigilance:3,Ego:0,Logic:4},traits:['Audience','Combat Reflexes','Free Running','Inventor','Scientific Expertise'],tags:['Heroic','Secret Identity'],powers:['Sentido Aranha','Escalar Paredes','Balanço com Teia','Agarrão com Teia','Golpe Brutal','Ataques Rápidos','Arremesso Rápido']}),
    wolverine: hero('wolverine','Wolverine','James Howlett / Logan',4,{image:'assets/portraits/hero-wolverine.jpg',pdf:'assets/pdfs/hero-wolverine.pdf',role:'Rastreador / duelista',hook:'A rivalidade com Dentes-de-Sabre coloca Logan no centro da campanha.',maxHealth:150,maxFocus:150,currentHealth:150,currentFocus:150,karma:4,initiative:'+4E',speed:'Correr 5 · Escalar 3 · Nadar 3 · Pular 3',movement:{run:5,climb:3,swim:3,jump:3},occupation:'Aventureiro',origin:'Mutante',teams:'X-Men, X-Force, Avengers',base:'Krakoa / móvel',stats:[['Health',150],['Focus',150],['Karma',4]],abilities:{Melee:7,Agility:2,Resilience:5,Vigilance:4,Ego:1,Logic:1},traits:['Battle Ready','Berserker','Combat Expert','Combat Reflexes','Situational Awareness'],tags:['Heroic','X-Gene','Hounded'],powers:['Garras de Adamantium','Fator de Cura','Sentidos Aguçados','Ataque Imparável','Ataques Furiosos','Bater e Correr','Pulo 1']}),
    cap: hero('cap','Capitão América','Steve Rogers',4,{image:'assets/portraits/hero-cap.jpg',pdf:'assets/pdfs/hero-capitao-america.pdf',role:'Líder tático',hook:'Hydra e Ossos Cruzados ligam Steve ao conflito principal.',maxHealth:90,maxFocus:120,currentHealth:90,currentFocus:120,karma:4,initiative:'+2E',occupation:'Soldado',origin:'Humano aprimorado',teams:'Avengers, Invaders',base:'Nova York',stats:[['Health',90],['Focus',120],['Karma',4]],abilities:{Melee:6,Agility:4,Resilience:3,Vigilance:3,Ego:2,Logic:2},traits:['Battle Ready','Combat Expert','Combat Reflexes','Public Speaking','Situational Awareness'],tags:['Heroic','Public Identity'],powers:['Escudo Ricochete','Bloqueio com Escudo','Liderança Inspiradora','Truque de Combate','Golpe Brutal','Arremesso Rápido']}),
    'iron-man': hero('iron-man','Homem de Ferro','Tony Stark',4,{image:'assets/portraits/hero-iron-man.png',role:'Artilharia / tecnologia',hook:'A tecnologia Stark é um dos pilares do conflito.',maxHealth:120,maxFocus:120,currentHealth:120,currentFocus:120,karma:4,initiative:'+2E',speed:'Correr 5 · Voo 18',movement:{run:5,flight:18},occupation:'Inventor / CEO',origin:'Armadura de alta tecnologia',teams:'Avengers',base:'Nova York',stats:[['Health',120],['Focus',120],['Karma',4]],abilities:{Melee:4,Agility:4,Resilience:4,Vigilance:3,Ego:3,Logic:7},traits:['Celebrity','Inventor','Scientific Expertise','Tech Reliance'],tags:['Heroic','Public Identity'],powers:['Rajada Repulsora','Voo','Sensores de Armadura','Mísseis','Unibeam','Campos de Força','Brilhantismo 2']}),
    thor: hero('thor','Thor','Thor Odinson',4,{image:'assets/portraits/hero-thor.png',role:'Tanque / energia',hook:'A energia asgardiana desequilibra a campanha.',maxHealth:180,maxFocus:90,currentHealth:180,currentFocus:90,karma:4,initiative:'+2',speed:'Correr 5 · Voo 20 · Pular 5',movement:{run:5,flight:20,jump:5},occupation:'Príncipe guerreiro',origin:'Asgardiano',teams:'Avengers',base:'Asgard / Terra',stats:[['Health',180],['Focus',90],['Karma',4]],abilities:{Melee:7,Agility:2,Resilience:6,Vigilance:2,Ego:3,Logic:1},traits:['Battle Ready','Famous','Mythic','Strong Willed'],tags:['Heroic','Public Identity'],powers:['Mjolnir','Voo','Trovão','Poderoso 2','Ataque de Área','Arremesso de Mjolnir','Invulnerabilidade Parcial']}),
    cyclops: hero('cyclops','Ciclope','Scott Summers',4,{image:'assets/portraits/hero-cyclops.png',role:'Líder / precisão',hook:'Coordena a equipe sob pressão constante.',maxHealth:90,maxFocus:120,currentHealth:90,currentFocus:120,karma:4,initiative:'+2E',occupation:'Líder dos X-Men',origin:'Mutante',teams:'X-Men',base:'Krakoa / móvel',stats:[['Health',90],['Focus',120],['Karma',4]],abilities:{Melee:4,Agility:4,Resilience:3,Vigilance:4,Ego:2,Logic:3},traits:['Battle Ready','Combat Reflexes','Leadership','Situational Awareness'],tags:['Heroic','X-Gene'],powers:['Rajada Óptica','Rajada Precisa','Rajada de Supressão','Comando de Campo','Disparo Ricochete']}),
    storm: hero('storm','Tempestade','Ororo Munroe',4,{image:'assets/portraits/hero-storm.png',role:'Controle de campo / clima',hook:'Manipula a batalha em larga escala.',maxHealth:90,maxFocus:120,currentHealth:90,currentFocus:120,karma:4,initiative:'+2',speed:'Correr 5 · Voo 12',movement:{run:5,flight:12},occupation:'Rainha / heroína',origin:'Mutante',teams:'X-Men',base:'Krakoa / móvel',stats:[['Health',90],['Focus',120],['Karma',4]],abilities:{Melee:3,Agility:4,Resilience:3,Vigilance:3,Ego:4,Logic:2},traits:['Empathic','Leadership','Weather Sense'],tags:['Heroic','X-Gene'],powers:['Controle Climático','Raio','Ventos Cortantes','Voo','Névoa','Tempestade em Área']}),
    "iceman": hero("iceman","Homem de Gelo","Bobby Drake",4,{"role":"Controle de área / defesa","hook":"Bobby trava corredores, ergue coberturas e desacelera tropas inteiras com gelo instantâneo.","maxHealth":120,"maxFocus":90,"currentHealth":120,"currentFocus":90,"karma":4,"healthDR":"—","focusDR":"—","initiative":"+1","speed":"Correr 5 · Deslizar 12 · Escalar 3","movement":{"run":5,"slide":12,"climb":3},"occupation":"Herói mutante","origin":"Mutante","teams":"X-Men, X-Factor, Champions","base":"Krakoa / móvel","stats":[["Health",120],["Focus",90],["Karma",4]],"abilities":{"Melee":3,"Agility":4,"Resilience":4,"Vigilance":2,"Ego":1,"Logic":2},"traits":["Cool Under Pressure","Creative","Team Player"],"tags":["Heroic","X-Gene"],"powers":["Construtos de Gelo","Deslizamento no Gelo","Muralha de Gelo","Rajada Congelante","Prisão de Gelo","Congelar Superfícies","Forma de Gelo"]}),
    gambit: hero('gambit','Gambit','Remy LeBeau',4,{image:'assets/portraits/hero-gambit.png',role:'Mobilidade / dano explosivo',hook:'Rouba, engana e resolve situações improváveis.',maxHealth:90,maxFocus:90,currentHealth:90,currentFocus:90,karma:4,initiative:'+3',speed:'Correr 6 · Escalar 4 · Pular 4',movement:{run:6,climb:4,jump:4,swim:3},occupation:'Ladrão / aventureiro',origin:'Mutante',teams:'X-Men',base:'Móvel',stats:[['Health',90],['Focus',90],['Karma',4]],abilities:{Melee:4,Agility:6,Resilience:3,Vigilance:2,Ego:2,Logic:2},traits:['Beguiling','Criminal Connections','Free Running','Lucky'],tags:['Heroic','X-Gene'],powers:['Cartas Cinéticas','Bastão de Combate','Acrobacia','Explosão Cinética','Arremesso Preciso']}),
    "mr-fantastic": hero("mr-fantastic","Senhor Fantástico","Reed Richards",4,{"role":"Gênio tático / controle elástico","hook":"Reed estabiliza portais, analisa ameaças cósmicas e vira a mente científica da equipe.","maxHealth":120,"maxFocus":120,"currentHealth":120,"currentFocus":120,"karma":4,"healthDR":"—","focusDR":"—","initiative":"+1","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3 · Alongamento 8","movement":{"run":5,"climb":3,"swim":3,"jump":3},"occupation":"Cientista / líder explorador","origin":"Mutação cósmica","teams":"Fantastic Four, Illuminati","base":"Edifício Baxter","stats":[["Health",120],["Focus",120],["Karma",4]],"abilities":{"Melee":3,"Agility":2,"Resilience":4,"Vigilance":3,"Ego":2,"Logic":7},"traits":["Brilliant","Inventor","Leadership","Scientific Expertise"],"tags":["Heroic","Public Identity","Lab Access"],"powers":["Elasticidade","Alongamento Extremo","Imobilização Elástica","Golpe Alongado","Defesa Flexível","Rebote Elástico","Mente Científica"]}),
    "invisible-woman": hero("invisible-woman","Mulher-Invisível","Sue Storm",4,{"role":"Defesa / utilidade / controle","hook":"Sue protege a linha de frente, torna aliados invisíveis e domina o espaço com campos de força.","maxHealth":90,"maxFocus":120,"currentHealth":90,"currentFocus":120,"karma":4,"healthDR":"—","focusDR":"—","initiative":"+2","speed":"Correr 5 · Voo 8 · Escalar 3 · Nadar 3 · Pular 3","movement":{"run":5,"flight":8,"climb":3,"swim":3,"jump":3},"occupation":"Aventureira / cientista","origin":"Mutação cósmica","teams":"Fantastic Four","base":"Edifício Baxter","stats":[["Health",90],["Focus",120],["Karma",4]],"abilities":{"Melee":2,"Agility":3,"Resilience":3,"Vigilance":3,"Ego":5,"Logic":3},"traits":["Leadership","Protective","Strong Willed"],"tags":["Heroic","Public Identity"],"powers":["Invisibilidade","Invisibilidade em Grupo","Campos de Força","Barreira de Força","Prisão de Força","Rajada de Força","Plataforma de Força"]}),
    "human-torch": hero("human-torch","Tocha Humana","Johnny Storm",4,{"role":"Mobilidade / dano em área","hook":"Johnny entra pelo alto, incendeia o campo de batalha e pressiona múltiplos alvos de uma só vez.","maxHealth":90,"maxFocus":90,"currentHealth":90,"currentFocus":90,"karma":4,"healthDR":"—","focusDR":"—","initiative":"+3","speed":"Correr 5 · Voo 20","movement":{"run":5,"flight":20},"occupation":"Aventureiro / celebridade","origin":"Mutação cósmica","teams":"Fantastic Four","base":"Edifício Baxter","stats":[["Health",90],["Focus",90],["Karma",4]],"abilities":{"Melee":3,"Agility":5,"Resilience":3,"Vigilance":2,"Ego":2,"Logic":1},"traits":["Celebrity","Hotheaded","Fearless"],"tags":["Heroic","Public Identity"],"powers":["Chamas","Voo","Rajada Ígnea","Bola de Fogo","Parede de Fogo","Nova Flamejante","Corpo em Chamas"]}),
    "thing": hero("thing","Coisa","Ben Grimm",4,{"role":"Tanque / protetor","hook":"Ben segura o avanço inimigo, absorve o pior da pancadaria e abre caminho na força bruta.","maxHealth":180,"maxFocus":60,"currentHealth":180,"currentFocus":60,"karma":4,"healthDR":"-1","focusDR":"—","initiative":"+1","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 4","movement":{"run":5,"climb":3,"swim":3,"jump":4},"occupation":"Piloto / herói","origin":"Mutação cósmica","teams":"Fantastic Four","base":"Edifício Baxter","stats":[["Health",180],["Focus",60],["Karma",4]],"abilities":{"Melee":7,"Agility":1,"Resilience":6,"Vigilance":2,"Ego":2,"Logic":1},"traits":["Battle Ready","Determination","Strong Willed"],"tags":["Heroic","Public Identity"],"powers":["Poderoso 2","Golpe Sísmico","Agarrão Esmagador","Durabilidade Rochosa","Saltão","Proteção de Aliado","Investida Devastadora"]}),
    "daredevil": hero("daredevil","Demolidor","Matt Murdock",4,{"role":"Sentidos / acrobacia / precisão","hook":"O radar sensorial de Matt detecta emboscadas, mentiras e rotas que outros nem percebem.","maxHealth":90,"maxFocus":90,"currentHealth":90,"currentFocus":90,"karma":4,"healthDR":"—","focusDR":"—","initiative":"+4E","speed":"Correr 6 · Escalar 4 · Nadar 3 · Pular 4","movement":{"run":6,"climb":4,"swim":3,"jump":4},"occupation":"Advogado / vigilante","origin":"Humano aprimorado","teams":"Defenders, Marvel Knights","base":"Hell’s Kitchen","stats":[["Health",90],["Focus",90],["Karma",4]],"abilities":{"Melee":6,"Agility":6,"Resilience":2,"Vigilance":5,"Ego":2,"Logic":2},"traits":["Blind but Aware","Combat Reflexes","Free Running","Situational Awareness"],"tags":["Heroic","Secret Identity","Streetwise"],"powers":["Sentidos Aguçados","Radar Sensorial","Bastão Billy Club","Acrobacia","Ripostar","Manobra Desarmante","Ataque Preciso"]}),
    "luke-cage": hero("luke-cage","Luke Cage","Carl Lucas / Luke Cage",4,{"role":"Tanque urbano / guarda-costas","hook":"Luke absorve pressão física extrema, protege civis e ancora a equipe em combate corpo a corpo.","maxHealth":180,"maxFocus":60,"currentHealth":180,"currentFocus":60,"karma":4,"healthDR":"-1","focusDR":"—","initiative":"+1","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3","movement":{"run":5,"climb":3,"swim":3,"jump":3},"occupation":"Herói de aluguel","origin":"Experimento científico","teams":"Heroes for Hire, Defenders, Avengers","base":"Nova York","stats":[["Health",180],["Focus",60],["Karma",4]],"abilities":{"Melee":6,"Agility":2,"Resilience":6,"Vigilance":2,"Ego":2,"Logic":1},"traits":["Streetwise","Determination","Fearless"],"tags":["Heroic","Public Identity"],"powers":["Pele Imbatível","Poderoso 2","Golpe Brutal","Proteção de Aliado","Investida Pesada","Quebra-Linhas","Agarrão de Contenção"]}),
    "deadpool": hero("deadpool","Deadpool","Wade Wilson",4,{"role":"Caos / regeneração / dano híbrido","hook":"Wade cria distração, sobrevive ao absurdo e mantém pressão constante com lâminas e armas de fogo.","maxHealth":150,"maxFocus":90,"currentHealth":150,"currentFocus":90,"karma":4,"healthDR":"—","focusDR":"—","initiative":"+3","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3","movement":{"run":5,"climb":3,"swim":3,"jump":3},"occupation":"Mercenário","origin":"Mutante alterado","teams":"X-Force, independente","base":"Móvel","stats":[["Health",150],["Focus",90],["Karma",4]],"abilities":{"Melee":5,"Agility":5,"Resilience":5,"Vigilance":2,"Ego":2,"Logic":1},"traits":["Annoying","Combat Expert","Weird","Hard to Kill"],"tags":["Heroic-ish","Public Identity"],"powers":["Fator de Cura","Katana Dupla","Pistolas","Ataques Rápidos","Tiro Duplo","Bater e Correr","Quebrar a Quarta Parede"]}),
    "black-panther": hero("black-panther","Pantera Negra","T'Challa",4,{"maxHealth":90,"maxFocus":90,"currentHealth":90,"currentFocus":90,"karma":4,"healthDR":"-2","focusDR":"—","initiative":"+3","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3","movement":{"run":5,"climb":3,"swim":3,"jump":3},"occupation":"Líder","origin":"Alta Tecnologia, Magia","teams":"Agents of Wakanda, Avengers, Fantastic Four, Panther Cult, Ultimates","base":"Wakanda","role":"Líder / combatente tático","hook":"Combina treinamento, tecnologia wakandana e comando de campo.","abilities":{"Melee":7,"Agility":4,"Resilience":3,"Vigilance":3,"Ego":2,"Logic":1},"traits":["Combat Reflexes","Extraordinary Origin","Famous","Fearless","Presence","Tech Reliance"],"tags":["Authority","Enemy: Killmonger","Headquarters: Wakanda","Heroic","Obligation: Wakanda","Powerful","Public Identity","Rich","Supernatural"],"powers":["Heightened Senses 1","Iconic Weapon: Electrified Vibranium Claws","Inspiration","Mighty 1","Sturdy 2","Attack Stance","Brace for Impact","Chain Strikes","Counterstrike Technique","Do This All Day","Fast Strikes","Always Ready","Battle Plan","Change of Plans","Combat Support","Focus Fire","Operations Center"],"image":"assets/portraits/hero-black-panther.png","pdf":"assets/pdfs/hero-black-panther.pdf","source":"Core Rulebook","stats":[["Health",90],["Focus",90],["Karma",4]]}),
    "captain-marvel": hero("captain-marvel","Capitã Marvel","Carol Danvers",6,{"maxHealth":180,"maxFocus":180,"currentHealth":180,"currentFocus":180,"karma":6,"healthDR":"-3","focusDR":"—","initiative":"+5E","speed":"Correr 6 · Escalar 3 · Nadar 3 · Pular 3 · Voo 36","movement":{"run":6,"climb":3,"swim":3,"jump":3,"flight":36},"occupation":"Militar, Espiã","origin":"Alienígena","teams":"Avengers, Ultimates, U.S. Air Force","base":"Nova York","role":"Artilharia cósmica / tanque aéreo","hook":"Controle de energia e mobilidade aérea em escala cósmica.","abilities":{"Melee":7,"Agility":6,"Resilience":6,"Vigilance":5,"Ego":5,"Logic":2},"traits":["Battle Ready","Combat Expert","Combat Reflexes","Connections: Espionage","Connections: Military","Enduring Constitution","Extra Occupation","Fearless","Leverage","Piloting","Situational Awareness"],"tags":["Alien Heritage","Authority","Black Market Access","Enemy: Magnitron (Yon-Rogg)","Heroic","Linguist: Arabic, English, Imperial Shi'ar, Kree, Russian","Public Identity"],"powers":["Accuracy 4","Combat Trickery","Discipline 3","Energy Absorption","Environmental Protection","Flight 2","Healing Factor","Inspiration","Mighty 4","Sturdy 3","Elemental Barrage","Elemental Barrier","Elemental Blast","Elemental Burst","Elemental Protection","Elemental Reinforcement","Supernova"],"image":"assets/portraits/hero-captain-marvel.png","pdf":"assets/pdfs/hero-captain-marvel.pdf","source":"Core Rulebook","stats":[["Health",180],["Focus",180],["Karma",6]]}),
    "doctor-strange": hero("doctor-strange","Doutor Estranho","Stephen Vincent Strange",6,{"maxHealth":90,"maxFocus":210,"currentHealth":90,"currentFocus":210,"karma":6,"healthDR":"—","focusDR":"—","initiative":"+7","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3 · Voo 30","movement":{"run":5,"climb":3,"swim":3,"jump":3,"flight":30},"occupation":"Profissional da Saúde","origin":"Magia: Feitiçaria","teams":"Avengers, Strange Academy","base":"Nova York","role":"Feiticeiro / controle / suporte","hook":"Resolve ameaças místicas e controla o campo com feitiços de alta complexidade.","abilities":{"Melee":3,"Agility":3,"Resilience":3,"Vigilance":7,"Ego":9,"Logic":6},"traits":["Abrasive","Clinician","Combat Reflexes","First Aid","Font of Information","Honest","Iron Will","Loner"],"tags":["Enemy: Baron Mordo","Enemy: Dormammu","Heroic","Public Identity","Prescription Pad","Sorcerous","Supernatural"],"powers":["Accuracy 1","Brilliance 1","Discipline 4","Flight 2","Astral Form","Bolts of Balthakk","Crimson Bands of Cyttorak","Dispel Spell","Flames of the Faltine","Icy Tendrils of Ikthalon","Images of Ikonn","Mist of Morpheus","Mists of Munnopor","Shield of the Seraphim","Summon Portal","Vapors of Valtorr","Winds of Watoomb","Attack Stance","Defense Stance","Do This All Day","Telepathic Link","Telepathic Network"],"image":"assets/portraits/hero-doctor-strange.png","pdf":"assets/pdfs/hero-doctor-strange.pdf","source":"Core Rulebook","stats":[["Health",90],["Focus",210],["Karma",6]]}),
    "hulk": hero("hulk","Hulk","Robert Bruce Banner",6,{"maxHealth":270,"maxFocus":150,"currentHealth":270,"currentFocus":150,"karma":"—","healthDR":"-3","focusDR":"-2","initiative":"+4","speed":"Correr 6 · Escalar 3 · Nadar 3 · Pular 36","movement":{"run":6,"climb":3,"swim":3,"jump":36},"occupation":"Cientista","origin":"Ciência Estranha: Mutação Gama","teams":"Avengers, S.H.I.E.L.D., U.S. Hulk Operations","base":"Móvel","role":"Tanque extremo / destruição de cenário","hook":"Força e durabilidade de escala máxima com progressão de fúria.","abilities":{"Melee":9,"Agility":3,"Resilience":9,"Vigilance":4,"Ego":2,"Logic":8},"traits":["Battle Ready","Berserker","Big (Reach 2)","Enduring Constitution","Enhanced Physique","Inventor","Loner","Scientific Expertise","Weird"],"tags":["Alternate Form (Gamma Forms)","Enemy: Abomination","Enemy: Leader","Extreme Appearance","Green Door","Immunity: Gamma Radiation","Lab Access","Public Identity","Radioactive"],"powers":["Anger","Brilliance 2","Healing Factor","Mighty 4","Sturdy 3","Uncanny 2","Banging Heads","Clobber","Crushing Grip","Ground-Shaking Stomp","Immovable","Jump 3","Quick Toss","Smash","Unrelenting Smash"],"image":"assets/portraits/hero-hulk.png","pdf":"assets/pdfs/hero-hulk.pdf","source":"Core Rulebook","stats":[["Health",270],["Focus",150],["Karma","—"]]}),
    "hawkeye": hero("hawkeye","Gavião Arqueiro","Clinton Francis \"Clint\" Barton",2,{"maxHealth":30,"maxFocus":60,"currentHealth":30,"currentFocus":60,"karma":2,"healthDR":"—","focusDR":"—","initiative":"+2","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3","movement":{"run":5,"climb":3,"swim":3,"jump":3},"occupation":"Artista / Entertainer","origin":"Treinamento Especial","teams":"Avengers, Thunderbolts","base":"Brooklyn, Nova York","role":"Precisão / combate à distância","hook":"Pressiona alvos importantes com tiro de precisão e controle de alcance.","abilities":{"Melee":2,"Agility":4,"Resilience":1,"Vigilance":2,"Ego":0,"Logic":1},"traits":["Combat Reflexes","Determination","Famous","Fearless","Presence","Public Speaking"],"tags":["Auditory Issues","Heroic","Public Identity","Signature Weapon: Bow and Arrow","Streetwise"],"powers":["Accuracy 2","Slow-Motion Dodge","Fast Strikes","Leg Sweep","Double Tap","Stopping Power","Sniping"],"image":"assets/portraits/hero-hawkeye.png","pdf":"assets/pdfs/hero-hawkeye.pdf","source":"Core Rulebook","stats":[["Health",30],["Focus",60],["Karma",2]]}),
    "scarlet-witch": hero("scarlet-witch","Feiticeira Escarlate","Wanda Maximoff",5,{"maxHealth":90,"maxFocus":150,"currentHealth":90,"currentFocus":150,"karma":5,"healthDR":"—","focusDR":"—","initiative":"+5E","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3 · Voo 25","movement":{"run":5,"climb":3,"swim":3,"jump":3,"flight":25},"occupation":"Aventureira","origin":"Ciência Estranha, Magia: Magia do Caos","teams":"Brotherhood of Evil Mutants, X-Men","base":"Krakoa","role":"Controle de realidade / magia","hook":"Manipula probabilidade, feitiços e poderes adversários.","abilities":{"Melee":2,"Agility":2,"Resilience":3,"Vigilance":5,"Ego":8,"Logic":5},"traits":["Combat Expert","Connections: Super Heroes","Dealmaker","Extraordinary Origin","Fearless","Font of Information","Situational Awareness","Weird"],"tags":["Black Market Access","Chaotic","Heroic","Hounded","Public Identity","Sorcerous","Supernatural"],"powers":["Discipline 2","Flight 2","Astral Form","Bolts of Balthakk","Crimson Bands of Cyttorak","Hex Bolt","Jinx","Powerful Hex","Probability-Manipulation Hex","Protection Hex","Dispel Spell","Flames of the Faltine","Images of Ikonn","Mists of Morpheus","Shield of the Seraphim","Summon Portal","Winds of Watoomb","Boost Powers","Dampen Power"],"image":"assets/portraits/hero-scarlet-witch.png","pdf":"assets/pdfs/hero-scarlet-witch.pdf","source":"Core Rulebook","stats":[["Health",90],["Focus",150],["Karma",5]]}),
    "shang-chi": hero("shang-chi","Shang-Chi","Zheng Shang-Chi",4,{"maxHealth":90,"maxFocus":150,"currentHealth":90,"currentFocus":150,"karma":4,"healthDR":"—","focusDR":"—","initiative":"+5E","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3","movement":{"run":5,"climb":3,"swim":3,"jump":3},"occupation":"Espião","origin":"Treinamento Especial","teams":"Agents of Atlas, Avengers, Five Weapons Society, Heroes for Hire, Protectors","base":"Chinatown, Nova York","role":"Mestre marcial / controle corpo a corpo","hook":"Exerce pressão contínua com a árvore completa de artes marciais.","abilities":{"Melee":7,"Agility":3,"Resilience":3,"Vigilance":5,"Ego":1,"Logic":1},"traits":["Combat Expert","Combat Reflexes","Connections: Espionage","Determination","Free Running","Leverage","Situational Awareness"],"tags":["Black Market Access","Heroic","Linguist: Chinese, English","Public Identity"],"powers":["Brawling","Attack Stance","Brace for Impact","Chain Strikes","Counterstrike Technique","Crushing Grip","Defense Stance","Do This All Day","Fast Strikes","Flying Double Kick","Focused Strike","Grappling Technique","Leaping Leglock","Leg Sweep","Regain Focus","Reverse-Momentum Throw","Spin & Throw","Unflappable Poise","Untouchable Position"],"image":"assets/portraits/hero-shang-chi.png","pdf":"assets/pdfs/hero-shang-chi.pdf","source":"Core Rulebook","stats":[["Health",90],["Focus",150],["Karma",4]]}),
    "she-hulk": hero("she-hulk","Mulher-Hulk","Jennifer Walters",4,{"maxHealth":90,"maxFocus":90,"currentHealth":90,"currentFocus":90,"karma":4,"healthDR":"-2","focusDR":"—","initiative":"+3","speed":"Correr 6 · Escalar 3 · Nadar 3 · Pular 24","movement":{"run":6,"climb":3,"swim":3,"jump":24},"occupation":"Advogada","origin":"Ciência Estranha: Mutação Gama","teams":"Avengers, Fantastic Four","base":"Nova York","role":"Tanque / força / presença social","hook":"Combina poder gama com utilidade jurídica e social.","abilities":{"Melee":5,"Agility":4,"Resilience":3,"Vigilance":3,"Ego":1,"Logic":6},"traits":["Big (Reach 2)","Combat Expert","Dealmaker","Fearless","Interrogation","Legal Eagle","Public Speaking","Weird"],"tags":["Alternate Form (Gamma Forms)","Extreme Appearance","Green Door","Immunity: Gamma Radiation","Heroic","Public Identity","Radioactive"],"powers":["Accuracy 1","Environmental Protection","Mighty 4","Sturdy 2","Clobber","Crushing Grip","Ground-Shaking Stomp","Jump 3","Quick Toss","Smash","Unrelenting Smash"],"image":"assets/portraits/hero-she-hulk.png","pdf":"assets/pdfs/hero-she-hulk.pdf","source":"Core Rulebook","stats":[["Health",90],["Focus",90],["Karma",4]]}),
    "vision": hero("vision","Visão","Vision",4,{"maxHealth":90,"maxFocus":90,"currentHealth":90,"currentFocus":90,"karma":4,"healthDR":"-3","focusDR":"—","initiative":"+3","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3 · Voo 20","movement":{"run":5,"climb":3,"swim":3,"jump":3,"flight":20},"occupation":"Aventureiro","origin":"Alta Tecnologia: Android","teams":"Avengers","base":"Arlington, Virginia","role":"Faseamento / energia / utilidade","hook":"Alterna defesa por densidade, voo e ataques energéticos.","abilities":{"Melee":4,"Agility":4,"Resilience":3,"Vigilance":3,"Ego":1,"Logic":5},"traits":["Connections: Super Heroes","Eidetic Memory","Fearless","Font of Information","Gearhead","Scientific Expertise","Tech Reliance"],"tags":["A.I.","Black Market Access","Extreme Appearance","Heroic","Public Identity"],"powers":["Brilliance 2","Disguise","Flight 2","Mighty 2","Sturdy 3","Elemental Barrage","Elemental Blast","Elemental Burst","Disrupt Electronics","Disrupt Nerves","Disrupt Person","Partial Phase","Phase Self"],"image":"assets/portraits/hero-vision.png","pdf":"assets/pdfs/hero-vision.pdf","source":"Core Rulebook","stats":[["Health",90],["Focus",90],["Karma",4]]}),
    "war-machine": hero("war-machine","Máquina de Combate","James Rupert \"Jim\" Rhodes",4,{"maxHealth":90,"maxFocus":120,"currentHealth":90,"currentFocus":120,"karma":4,"healthDR":"-2","focusDR":"—","initiative":"+3E","speed":"Correr 6 · Escalar 3 · Nadar 3 · Pular 3 · Voo 24","movement":{"run":6,"climb":3,"swim":3,"jump":3,"flight":24},"occupation":"Militar","origin":"Alta Tecnologia: Traje de Combate","teams":"Avengers, S.H.I.E.L.D.","base":"Nova York","role":"Artilharia pesada / suporte aéreo","hook":"Combina rajadas de energia e arsenal tático de longo alcance.","abilities":{"Melee":2,"Agility":6,"Resilience":3,"Vigilance":3,"Ego":2,"Logic":4},"traits":["Battle Ready","Combat Expert","Connections: Military","Gearhead","Glibness","Piloting","Situational Awareness","Tech Reliance"],"tags":["Extreme Appearance (in battle suit)","Headquarters: Stark Tower","Heroic","Lab Access","Public Identity"],"powers":["Accuracy 2","Flight 2","Sturdy 2","Elemental Blast","Elemental Burst","Elemental Push","Covering Fire","Double Tap","Headshot","Kill Zone","Return Fire","Snap Shooting","Stopping Power","Suppressive Fire","Weapons Blazing"],"image":"assets/portraits/hero-war-machine.png","pdf":"assets/pdfs/hero-war-machine.pdf","source":"Core Rulebook","stats":[["Health",90],["Focus",120],["Karma",4]]}),
  },
  villains: {
    octopus: villain('octopus','Doutor Octopus','Otto Octavius',4,'AMEAÇA',{image:'assets/portraits/villain-octopus.jpg',pdf:'assets/pdfs/villain-doutor-octopus.pdf',role:'Cientista / ameaça tática',hook:'Primeiro grande suspeito da conspiração.',maxHealth:90,maxFocus:60,currentHealth:90,currentFocus:60,initiative:'+2',speed:'Correr 5 · Escalar 5 · Nadar 3 · Pular 5',movement:{run:5,climb:5,swim:3,jump:5},occupation:'Cientista',origin:'Alta tecnologia / ciência bizarra',teams:'Sinister Six, Masters of Evil',base:'Nova York',abilities:{Melee:4,Agility:3,Resilience:3,Vigilance:2,Ego:4,Logic:5},traits:['Inventor','Scientific Expertise','Tech Reliance'],tags:['Villainous','Public Identity'],powers:['Membros Adicionais','Golpear Cabeças','Agarrão Esmagador','Alcance Estendido','Pulo 1']}),
    sabretooth: villain('sabretooth','Dentes-de-Sabre','Victor Creed',4,'AMEAÇA',{image:'assets/portraits/villain-sabretooth.jpg',pdf:'assets/pdfs/villain-dentes-de-sabre.pdf',role:'Caçador mutante',hook:'Rival pessoal de Wolverine.',maxHealth:180,maxFocus:150,currentHealth:180,currentFocus:150,healthDR:'-1',initiative:'+4E',occupation:'Mercenário',origin:'Mutante / cibernética',teams:'Marauders, Brotherhood',base:'Krakoa / móvel',abilities:{Melee:7,Agility:4,Resilience:6,Vigilance:4,Ego:0,Logic:0},traits:['Battle Ready','Berserker','Combat Reflexes','Stealthy'],tags:['Villainous','X-Gene'],powers:['Fator de Cura','Sentidos Aguçados','Ataque Cruel','Frenesi Giratório','Pulo 1']}),
    crossbones: villain('crossbones','Ossos Cruzados','Brock Rumlow',3,'AMEAÇA',{image:'assets/portraits/villain-crossbones.jpg',pdf:'assets/pdfs/villain-ossos-cruzados.pdf',role:'Operativo Hydra',hook:'Ataque tático ligado ao passado de Steve.',maxHealth:90,maxFocus:90,currentHealth:90,currentFocus:90,initiative:'+2E',speed:'Correr 6 · Escalar 3 · Nadar 3 · Pular 3',movement:{run:6,climb:3,swim:3,jump:3},occupation:'Mercenário',origin:'Treinamento especial',teams:'Hydra, Thunderbolts',base:'Móvel',abilities:{Melee:4,Agility:5,Resilience:3,Vigilance:2,Ego:0,Logic:1},traits:['Battle Ready','Combat Expert','Connections: Military'],tags:['Villainous','Signature Weapon'],powers:['Precisão 2','Tiro Duplo','Poder de Parada','Aparar à Queima-Roupa']}),
    goblin: villain('goblin','Duende Verde','Norman Osborn',4,'AMEAÇA',{image:'assets/portraits/villain-goblin.jpg',pdf:'assets/pdfs/villain-duende-verde.pdf',role:'Incursor imprevisível',hook:'Invade o projeto para roubar tecnologia.',maxHealth:120,maxFocus:60,currentHealth:120,currentFocus:60,healthDR:'-1',initiative:'+2',speed:'Correr 6 · Voo 24',movement:{run:6,flight:24,swim:3,climb:3},occupation:'Magnata / criminoso',origin:'Ciência bizarra',teams:'Sinister Six, Dark Avengers',base:'Nova York',abilities:{Melee:5,Agility:5,Resilience:4,Vigilance:2,Ego:1,Logic:3},traits:['Celebrity','Inventor','Weird'],tags:['Villainous','Public Identity'],powers:['Planador','Bombas de Abóbora','Ataque Aéreo','Poderoso 1','Arremesso Rápido']}),
    sinister: villain('sinister','Senhor Sinistro','Nathaniel Essex',5,'CHEFE FINAL',{image:'assets/portraits/villain-sinister.jpg',pdf:'assets/pdfs/villain-senhor-sinistro.pdf',role:'Vilão final',hook:'Mentor oculto do Projeto Arachne.',maxHealth:180,maxFocus:120,currentHealth:180,currentFocus:120,initiative:'+3',occupation:'Geneticista',origin:'Mutante / ciência bizarra',teams:'Marauders',base:'Laboratório Essex',abilities:{Melee:5,Agility:3,Resilience:5,Vigilance:3,Ego:4,Logic:6},traits:['Brilliant','Extraordinary Origin','Scientific Expertise'],tags:['Villainous','Public Identity'],powers:['Regeneração','Telepatia limitada','Manipulação Genética','Rajada de Energia','Clonagem de Campo']}),
    "doom": villain("doom","Doutor Destino","Victor Von Doom",5,"CHEFE FINAL",{"role":"Monarca / tecnomago","hook":"Doom reúne tecnologia e magia para impor uma única realidade possível ao mundo.","maxHealth":180,"maxFocus":150,"currentHealth":180,"currentFocus":150,"karma":"—","healthDR":"-1","focusDR":"—","initiative":"+2","speed":"Correr 5 · Voo 10","movement":{"run":5,"flight":10},"occupation":"Monarca da Latvéria","origin":"Armadura mística e tecnológica","teams":"Latvéria, Masters of Evil","base":"Castelo de Doom","stats":[["Health",180],["Focus",150],["Karma","—"]],"abilities":{"Melee":5,"Agility":2,"Resilience":5,"Vigilance":3,"Ego":5,"Logic":6},"traits":["Brilliant","Inventor","Leader","Sorcerer","Tech Reliance"],"tags":["Villainous","Public Identity"],"powers":["Armadura de Doom","Rajada de Energia","Escudos Místicos","Voo","Brilhantismo 2","Comando Implacável","Magia de Batalha"]}),
    "loki": villain("loki","Loki","Loki Laufeyson",4,"AMEAÇA",{"role":"Manipulador / ilusões / magia","hook":"Loki semeia dúvidas, engana aliados e abre espaço para o plano principal florescer no caos.","maxHealth":90,"maxFocus":150,"currentHealth":90,"currentFocus":150,"karma":"—","healthDR":"—","focusDR":"—","initiative":"+2","speed":"Correr 5 · Voo 10","movement":{"run":5,"flight":10},"occupation":"Príncipe asgardiano","origin":"Asgardiano / magia","teams":"Asgard, Masters of Evil","base":"Asgard","stats":[["Health",90],["Focus",150],["Karma","—"]],"abilities":{"Melee":3,"Agility":3,"Resilience":4,"Vigilance":3,"Ego":6,"Logic":4},"traits":["Beguiling","Sorcerer","Weird","Deceiver"],"tags":["Villainous","Mythic"],"powers":["Ilusões","Duplicatas","Teleporte","Rajada Mística","Encantamento","Metamorfose","Trapaça Arcana"]}),
    "zemo": villain("zemo","Barão Zemo","Helmut Zemo",4,"AMEAÇA",{"role":"Estratégia / sabotagem / comando","hook":"Zemo transforma cada encontro em uma operação tática, explorando fraquezas e vantagens de terreno.","maxHealth":90,"maxFocus":90,"currentHealth":90,"currentFocus":90,"karma":"—","healthDR":"—","focusDR":"—","initiative":"+2","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3","movement":{"run":5,"climb":3,"swim":3,"jump":3},"occupation":"Terrorista / estrategista","origin":"Treinamento especial","teams":"Masters of Evil, Thunderbolts","base":"Europa / móvel","stats":[["Health",90],["Focus",90],["Karma","—"]],"abilities":{"Melee":4,"Agility":4,"Resilience":3,"Vigilance":3,"Ego":2,"Logic":4},"traits":["Leader","Tactician","Combat Expert"],"tags":["Villainous"],"powers":["Espadachim","Armas de Precisão","Truques Químicos","Plano de Batalha","Sabotagem","Comando Tático","Arremesso Preciso"]}),
    "abomination": villain("abomination","Abominável","Emil Blonsky",4,"AMEAÇA",{"role":"Brutamontes gama","hook":"A monstruosidade gama serve como teste de força viva para esmagar resistência e intimidar heróis.","maxHealth":210,"maxFocus":60,"currentHealth":210,"currentFocus":60,"karma":"—","healthDR":"-1","focusDR":"—","initiative":"+1","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 5","movement":{"run":5,"climb":3,"swim":3,"jump":5},"occupation":"Soldado / arma viva","origin":"Irradiação gama","teams":"Thunderbolts","base":"Móvel","stats":[["Health",210],["Focus",60],["Karma","—"]],"abilities":{"Melee":7,"Agility":1,"Resilience":7,"Vigilance":1,"Ego":1,"Logic":1},"traits":["Battle Ready","Bloodthirsty","Fearsome"],"tags":["Villainous"],"powers":["Poderoso 3","Salto Monumental","Arremesso Brutal","Investida Monstruosa","Onda de Impacto","Resistência Gama"]}),
    "enchantress": villain("enchantress","Encantadora","Amora",4,"AMEAÇA",{"role":"Magia / sedução / controle","hook":"Amora dobra vontades, abre passagens místicas e manipula o ritmo social e tático do conflito.","maxHealth":90,"maxFocus":150,"currentHealth":90,"currentFocus":150,"karma":"—","healthDR":"—","focusDR":"—","initiative":"+2","speed":"Correr 5 · Voo 8","movement":{"run":5,"flight":8},"occupation":"Feiticeira","origin":"Asgardiana / magia","teams":"Masters of Evil, Asgard","base":"Asgard","stats":[["Health",90],["Focus",150],["Karma","—"]],"abilities":{"Melee":2,"Agility":3,"Resilience":4,"Vigilance":2,"Ego":6,"Logic":3},"traits":["Beguiling","Sorcerer","Celebrity"],"tags":["Villainous","Mythic"],"powers":["Encantamento","Magia","Teleporte","Barreiras","Confusão Mística","Rajada Arcana","Controle Mental Leve"]}),
    "apocalypse": villain("apocalypse","Apocalypse","En Sabah Nur",6,"CHEFE FINAL",{"role":"Conquistador / mutante ancestral","hook":"Apocalypse quer acelerar a evolução pela força, dobrando o mundo à sua filosofia de sobrevivência.","maxHealth":240,"maxFocus":180,"currentHealth":240,"currentFocus":180,"karma":"—","healthDR":"-2","focusDR":"—","initiative":"+2","speed":"Correr 5 · Voo 12 · Pular 5","movement":{"run":5,"flight":12,"jump":5},"occupation":"Conquistador","origin":"Mutante ancestral","teams":"Akkaba, Cavaleiros","base":"Akkaba","stats":[["Health",240],["Focus",180],["Karma","—"]],"abilities":{"Melee":7,"Agility":3,"Resilience":7,"Vigilance":4,"Ego":5,"Logic":4},"traits":["Immortal","Leader","Mythic","Fearsome"],"tags":["Villainous","X-Gene"],"powers":["Mudança de Forma","Poderoso 3","Armas de Corpo","Regeneração","Rajada de Energia","Comando dos Cavaleiros","Tecnologia Celestial"]}),
    "mystique": villain("mystique","Mística","Raven Darkhölme",4,"AMEAÇA",{"role":"Infiltração / espionagem","hook":"Raven fabrica provas, assume rostos conhecidos e dissolve alianças por dentro.","maxHealth":90,"maxFocus":90,"currentHealth":90,"currentFocus":90,"karma":"—","healthDR":"—","focusDR":"—","initiative":"+4E","speed":"Correr 6 · Escalar 4 · Nadar 3 · Pular 4","movement":{"run":6,"climb":4,"swim":3,"jump":4},"occupation":"Espiã","origin":"Mutante","teams":"Brotherhood, Freedom Force","base":"Móvel","stats":[["Health",90],["Focus",90],["Karma","—"]],"abilities":{"Melee":4,"Agility":6,"Resilience":2,"Vigilance":4,"Ego":2,"Logic":2},"traits":["Disguise","Stealthy","Beguiling","Spy"],"tags":["Villainous","X-Gene"],"powers":["Metamorfose","Furtividade","Ataque Surpresa","Disfarce Perfeito","Infiltração","Tiro Preciso"]}),
    "juggernaut": villain("juggernaut","Juggernaut","Cain Marko",5,"RIVAL",{"role":"Aríete sobrenatural","hook":"Quando começa a correr, Juggernaut vira um desastre em movimento difícil de conter.","maxHealth":240,"maxFocus":60,"currentHealth":240,"currentFocus":60,"karma":"—","healthDR":"-2","focusDR":"—","initiative":"+0","speed":"Correr 6 · Escalar 2 · Nadar 2 · Pular 4","movement":{"run":6,"climb":2,"swim":2,"jump":4},"occupation":"Mercenário","origin":"Místico","teams":"Independente","base":"Móvel","stats":[["Health",240],["Focus",60],["Karma","—"]],"abilities":{"Melee":7,"Agility":0,"Resilience":8,"Vigilance":1,"Ego":1,"Logic":0},"traits":["Determination","Mythic","Fearsome"],"tags":["Villainous"],"powers":["Investida Imparável","Poderoso 3","Blindado","Tremor de Impacto","Momentum Infinito","Imóvel à Força"]}),
    "magneto": villain("magneto","Magneto","Erik Lehnsherr",5,"RIVAL",{"role":"Controle magnético / dominador de campo","hook":"Magneto pode virar o encontro inteiro contra quem depende de metal, armas ou estruturas urbanas.","maxHealth":120,"maxFocus":150,"currentHealth":120,"currentFocus":150,"karma":"—","healthDR":"—","focusDR":"—","initiative":"+2","speed":"Correr 5 · Voo 14","movement":{"run":5,"flight":14},"occupation":"Líder mutante","origin":"Mutante","teams":"Brotherhood, Krakoa","base":"Krakoa","stats":[["Health",120],["Focus",150],["Karma","—"]],"abilities":{"Melee":3,"Agility":2,"Resilience":4,"Vigilance":4,"Ego":5,"Logic":4},"traits":["Leadership","Strong Willed","Mythic"],"tags":["Villainous","X-Gene"],"powers":["Magnetismo","Voo","Barreiras Metálicas","Desarme em Massa","Campo Magnético","Prisão Metálica","Pulso Magnético"]}),
    "annihilus": villain("annihilus","Annihilus","",6,"CHEFE FINAL",{"role":"Senhor da Zona Negativa","hook":"Annihilus tenta abrir uma ponte permanente entre dimensões e engolir realidades em sua onda de conquista.","maxHealth":240,"maxFocus":120,"currentHealth":240,"currentFocus":120,"karma":"—","healthDR":"-1","focusDR":"—","initiative":"+2","speed":"Correr 6 · Voo 16","movement":{"run":6,"flight":16},"occupation":"Conquistador","origin":"Alienígena","teams":"Onda de Aniquilação","base":"Zona Negativa","stats":[["Health",240],["Focus",120],["Karma","—"]],"abilities":{"Melee":7,"Agility":3,"Resilience":7,"Vigilance":2,"Ego":3,"Logic":2},"traits":["Fearsome","Leader","Alien"],"tags":["Villainous"],"powers":["Voo","Cajado de Controle Cósmico","Enxame","Poderoso 2","Investida Alada","Ruptura Dimensional"]}),
    "super-skrull": villain("super-skrull","Super-Skrull","Kl'rt",5,"RIVAL",{"role":"Soldado supremo skrull","hook":"Kl’rt condensa os dons do Quarteto Fantástico em um oponente só, mudando de função a cada rodada.","maxHealth":180,"maxFocus":90,"currentHealth":180,"currentFocus":90,"karma":"—","healthDR":"—","focusDR":"—","initiative":"+2","speed":"Correr 5 · Voo 12","movement":{"run":5,"flight":12},"occupation":"Guerreiro skrull","origin":"Alienígena modificado","teams":"Império Skrull","base":"Espaço","stats":[["Health",180],["Focus",90],["Karma","—"]],"abilities":{"Melee":6,"Agility":4,"Resilience":5,"Vigilance":2,"Ego":2,"Logic":2},"traits":["Alien","Battle Ready","Adaptive"],"tags":["Villainous"],"powers":["Elasticidade","Chamas","Invisibilidade Parcial","Campo de Força","Poderoso 1","Voo","Mistura de Poderes"]}),
    "blastaar": villain("blastaar","Blastaar","",5,"RIVAL",{"role":"Força bruta / artilharia","hook":"Blastaar age como um tirano explosivo, destruindo cobertura e pressionando pelo volume de dano.","maxHealth":210,"maxFocus":60,"currentHealth":210,"currentFocus":60,"karma":"—","healthDR":"—","focusDR":"—","initiative":"+1","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 4","movement":{"run":5,"climb":3,"swim":3,"jump":4},"occupation":"Tirano","origin":"Alienígena","teams":"Zona Negativa","base":"Zona Negativa","stats":[["Health",210],["Focus",60],["Karma","—"]],"abilities":{"Melee":7,"Agility":1,"Resilience":7,"Vigilance":1,"Ego":2,"Logic":1},"traits":["Fearsome","Battle Ready"],"tags":["Villainous"],"powers":["Poderoso 3","Rajada de Energia","Salto Longo","Onda de Choque","Investida Pesada"]}),
    "molecule-man": villain("molecule-man","Homem-Molecular","Owen Reece",5,"WILDCARD",{"role":"Realidade instável / manipulação de matéria","hook":"Owen pode ser arma, pista ou catástrofe, alterando o cenário e a própria lógica do combate.","maxHealth":90,"maxFocus":180,"currentHealth":90,"currentFocus":180,"karma":"—","healthDR":"—","focusDR":"—","initiative":"+1","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3","movement":{"run":5,"climb":3,"swim":3,"jump":3},"occupation":"Operário","origin":"Manipulação molecular","teams":"Independente","base":"Desconhecida","stats":[["Health",90],["Focus",180],["Karma","—"]],"abilities":{"Melee":1,"Agility":1,"Resilience":2,"Vigilance":3,"Ego":5,"Logic":5},"traits":["Weird","Reality Warper","Unstable"],"tags":["Villainous","Wildcard"],"powers":["Manipulação Molecular","Reformar Matéria","Campo de Força","Controle de Área","Transmutação","Moldar Cobertura"]}),
    "kingpin": villain("kingpin","Wilson Fisk — Rei do Crime","Wilson Fisk",5,"CHEFE FINAL",{"role":"Chefe do submundo / comando","hook":"Fisk transforma recursos urbanos, capangas e influência política em uma máquina de guerra silenciosa.","maxHealth":180,"maxFocus":90,"currentHealth":180,"currentFocus":90,"karma":"—","healthDR":"—","focusDR":"—","initiative":"+1","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3","movement":{"run":5,"climb":3,"swim":3,"jump":3},"occupation":"Empresário / criminoso","origin":"Humano extraordinário","teams":"Império Fisk","base":"Hell’s Kitchen","stats":[["Health",180],["Focus",90],["Karma","—"]],"abilities":{"Melee":6,"Agility":1,"Resilience":6,"Vigilance":3,"Ego":4,"Logic":3},"traits":["Leader","Criminal Connections","Determination","Street Boss"],"tags":["Villainous","Public Identity"],"powers":["Poderoso 2","Rede de Informantes","Comando do Crime","Golpe Demolidor","Pressão Psicológica","Reforços do Submundo"]}),
    "bullseye": villain("bullseye","Mercenário / Bullseye","Lester",4,"AMEAÇA",{"role":"Assassino de precisão","hook":"Bullseye transforma qualquer objeto em arma letal e pune qualquer descuido de posicionamento.","maxHealth":90,"maxFocus":90,"currentHealth":90,"currentFocus":90,"karma":"—","healthDR":"—","focusDR":"—","initiative":"+4E","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3","movement":{"run":5,"climb":3,"swim":3,"jump":3},"occupation":"Assassino","origin":"Treinamento especial","teams":"Mercenários","base":"Móvel","stats":[["Health",90],["Focus",90],["Karma","—"]],"abilities":{"Melee":4,"Agility":6,"Resilience":2,"Vigilance":4,"Ego":1,"Logic":2},"traits":["Combat Reflexes","Psychopath","Precision"],"tags":["Villainous"],"powers":["Arremesso Letal","Precisão 3","Arma Improvisada","Tiro Impossível","Ricochete Mortal","Execução à Distância"]}),
    "ajax": villain("ajax","Ajax","Francis Freeman",4,"AMEAÇA",{"role":"Cirurgião da dor / duelista","hook":"Ajax surge como executor metódico, resistente à dor e perigosamente eficiente em curta distância.","maxHealth":120,"maxFocus":60,"currentHealth":120,"currentFocus":60,"karma":"—","healthDR":"—","focusDR":"—","initiative":"+2","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3","movement":{"run":5,"climb":3,"swim":3,"jump":3},"occupation":"Mercenário","origin":"Mutação artificial","teams":"Weapon X remnant","base":"Laboratório clandestino","stats":[["Health",120],["Focus",60],["Karma","—"]],"abilities":{"Melee":5,"Agility":4,"Resilience":4,"Vigilance":2,"Ego":1,"Logic":2},"traits":["Cruel","Tech Reliance","Hard to Hurt"],"tags":["Villainous"],"powers":["Lâminas","Golpe Brutal","Resistência à Dor","Investida Cortante","Execução Cirúrgica"]}),
    "tombstone": villain("tombstone","Tombstone","Lonnie Lincoln",4,"AMEAÇA",{"role":"Capanga premium / intimidação","hook":"Tombstone é a marreta do crime organizado, perfeito para esmagar resistência e impor medo.","maxHealth":180,"maxFocus":60,"currentHealth":180,"currentFocus":60,"karma":"—","healthDR":"-1","focusDR":"—","initiative":"+1","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3","movement":{"run":5,"climb":3,"swim":3,"jump":3},"occupation":"Criminoso","origin":"Mutação / química","teams":"Crime organizado","base":"Nova York","stats":[["Health",180],["Focus",60],["Karma","—"]],"abilities":{"Melee":6,"Agility":2,"Resilience":6,"Vigilance":2,"Ego":2,"Logic":1},"traits":["Fearsome","Streetwise"],"tags":["Villainous"],"powers":["Poderoso 2","Durabilidade","Atordoar","Golpe de Quebra-Osso","Presença Ameaçadora"]}),
    "madcap": villain("madcap","Madcap","",4,"AMEAÇA",{"role":"Caos instável / desordem mental","hook":"Madcap dobra a tensão social da cena, tornando a batalha imprevisível e emocionalmente corrosiva.","maxHealth":120,"maxFocus":120,"currentHealth":120,"currentFocus":120,"karma":"—","healthDR":"—","focusDR":"—","initiative":"+3","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3","movement":{"run":5,"climb":3,"swim":3,"jump":3},"occupation":"Anarquista","origin":"Química anômala","teams":"Independente","base":"Nova York","stats":[["Health",120],["Focus",120],["Karma","—"]],"abilities":{"Melee":3,"Agility":4,"Resilience":4,"Vigilance":1,"Ego":5,"Logic":1},"traits":["Annoying","Weird","Unhinged"],"tags":["Villainous"],"powers":["Regeneração","Insanidade Contagiosa","Imprevisibilidade","Riso Desequilibrante","Caos Inspirado"]}),
    "t-ray": villain("t-ray","T-Ray","",4,"AMEAÇA",{"role":"Sobrenatural / maldição","hook":"T-Ray arrasta a campanha para o horror oculto com maldições, construtos e mobilidade mística.","maxHealth":90,"maxFocus":120,"currentHealth":90,"currentFocus":120,"karma":"—","healthDR":"—","focusDR":"—","initiative":"+2","speed":"Correr 5 · Escalar 3 · Nadar 3 · Pular 3 · Teleporte 10","movement":{"run":5,"climb":3,"swim":3,"jump":3},"occupation":"Ocultista","origin":"Místico","teams":"Independente","base":"Desconhecida","stats":[["Health",90],["Focus",120],["Karma","—"]],"abilities":{"Melee":4,"Agility":2,"Resilience":3,"Vigilance":2,"Ego":4,"Logic":3},"traits":["Sorcerer","Weird","Vengeful"],"tags":["Villainous"],"powers":["Magia Negra","Teleporte","Amaldiçoar","Construto Místico","Rajada Necrótica","Invocação Sombria"]}),
    "elektra": villain("elektra","Elektra","Elektra Natchios",4,"WILDCARD",{"role":"Assassina / wildcard","hook":"Elektra atravessa a linha entre aliada e inimiga, sempre letal, silenciosa e difícil de prever.","maxHealth":90,"maxFocus":90,"currentHealth":90,"currentFocus":90,"karma":"—","healthDR":"—","focusDR":"—","initiative":"+4E","speed":"Correr 6 · Escalar 4 · Nadar 3 · Pular 4","movement":{"run":6,"climb":4,"swim":3,"jump":4},"occupation":"Assassina / ninja","origin":"Treinamento especial","teams":"The Hand","base":"Móvel","stats":[["Health",90],["Focus",90],["Karma","—"]],"abilities":{"Melee":6,"Agility":6,"Resilience":2,"Vigilance":4,"Ego":2,"Logic":1},"traits":["Stealthy","Combat Reflexes","Deadly"],"tags":["Villainous-ish"],"powers":["Sai Duplos","Acrobacia","Furtividade","Ataque Preciso","Ataque Surpresa","Dança das Lâminas"]}),
    'hydra-agent': villain('hydra-agent','Agente da Hydra','',2,'LACAIO',{image:'assets/portraits/villain-hydra-agent.jpg',pdf:'assets/pdfs/villain-agente-hydra.pdf',role:'Soldado de apoio',hook:'Capangas de linha da Hydra.',maxHealth:60,maxFocus:30,currentHealth:60,currentFocus:30,initiative:'+1',occupation:'Soldado',origin:'Treinamento especial',teams:'Hydra',base:'Varia',abilities:{Melee:2,Agility:2,Resilience:2,Vigilance:1,Ego:0,Logic:0},traits:['Battle Ready'],tags:['Villainous'],powers:['Rifle Hydra','Formação Tática']}),
    'aim-agent': villain('aim-agent','Agente da I.M.A.','',2,'LACAIO',{image:'assets/portraits/villain-aim-agent.jpg',pdf:'assets/pdfs/villain-agente-ima.pdf',role:'Técnico de apoio',hook:'Auxiliar tecnológico de laboratório.',maxHealth:50,maxFocus:50,currentHealth:50,currentFocus:50,initiative:'+1',occupation:'Cientista / operador',origin:'Treinamento especial',teams:'A.I.M.',base:'Laboratório móvel',abilities:{Melee:1,Agility:2,Resilience:1,Vigilance:1,Ego:0,Logic:3},traits:['Scientific Expertise'],tags:['Villainous'],powers:['Arma de Energia','Hack Rápido']})
  }
};


const CHARACTER_ASSETS = {
  heroes: {
    'iron-man': { image:'assets/portraits/hero-iron-man.png', pdf:'assets/pdfs/hero-iron-man.pdf' },
    thor: { image:'assets/portraits/hero-thor.png', pdf:'assets/pdfs/hero-thor.pdf' },
    cyclops: { image:'assets/portraits/hero-cyclops.png', pdf:'assets/pdfs/hero-cyclops.pdf' },
    storm: { image:'assets/portraits/hero-storm.png', pdf:'assets/pdfs/hero-storm.pdf' },
    iceman: { image:'assets/portraits/hero-iceman.png', pdf:'assets/pdfs/hero-iceman.pdf' },
    gambit: { image:'assets/portraits/hero-gambit.png', pdf:'assets/pdfs/hero-gambit.pdf' },
    'mr-fantastic': { image:'assets/portraits/hero-mr-fantastic.png', pdf:'assets/pdfs/hero-mr-fantastic.pdf' },
    'invisible-woman': { image:'assets/portraits/hero-invisible-woman.png', pdf:'assets/pdfs/hero-invisible-woman.pdf' },
    'human-torch': { image:'assets/portraits/hero-human-torch.png', pdf:'assets/pdfs/hero-human-torch.pdf' },
    thing: { image:'assets/portraits/hero-thing.png', pdf:'assets/pdfs/hero-thing.pdf' },
    daredevil: { image:'assets/portraits/hero-daredevil.png', pdf:'assets/pdfs/hero-daredevil.pdf' },
    'luke-cage': { image:'assets/portraits/hero-luke-cage.png', pdf:'assets/pdfs/hero-luke-cage.pdf' },
    deadpool: { image:'assets/portraits/hero-deadpool.png', pdf:'assets/pdfs/hero-deadpool.pdf' },
    "black-panther": { image:"assets/portraits/hero-black-panther.png", pdf:"assets/pdfs/hero-black-panther.pdf" },
    "captain-marvel": { image:"assets/portraits/hero-captain-marvel.png", pdf:"assets/pdfs/hero-captain-marvel.pdf" },
    "doctor-strange": { image:"assets/portraits/hero-doctor-strange.png", pdf:"assets/pdfs/hero-doctor-strange.pdf" },
    "hulk": { image:"assets/portraits/hero-hulk.png", pdf:"assets/pdfs/hero-hulk.pdf" },
    "hawkeye": { image:"assets/portraits/hero-hawkeye.png", pdf:"assets/pdfs/hero-hawkeye.pdf" },
    "scarlet-witch": { image:"assets/portraits/hero-scarlet-witch.png", pdf:"assets/pdfs/hero-scarlet-witch.pdf" },
    "shang-chi": { image:"assets/portraits/hero-shang-chi.png", pdf:"assets/pdfs/hero-shang-chi.pdf" },
    "she-hulk": { image:"assets/portraits/hero-she-hulk.png", pdf:"assets/pdfs/hero-she-hulk.pdf" },
    "vision": { image:"assets/portraits/hero-vision.png", pdf:"assets/pdfs/hero-vision.pdf" },
    "war-machine": { image:"assets/portraits/hero-war-machine.png", pdf:"assets/pdfs/hero-war-machine.pdf" },
  },
  villains: {
    doom: { image:'assets/portraits/villain-doom.png', pdf:'assets/pdfs/villain-doom.pdf' },
    loki: { image:'assets/portraits/villain-loki.png', pdf:'assets/pdfs/villain-loki.pdf' },
    zemo: { image:'assets/portraits/villain-zemo.png', pdf:'assets/pdfs/villain-zemo.pdf' },
    abomination: { image:'assets/portraits/villain-abomination.png', pdf:'assets/pdfs/villain-abomination.pdf' },
    enchantress: { image:'assets/portraits/villain-enchantress.png', pdf:'assets/pdfs/villain-enchantress.pdf' },
    apocalypse: { image:'assets/portraits/villain-apocalypse.png', pdf:'assets/pdfs/villain-apocalypse.pdf' },
    mystique: { image:'assets/portraits/villain-mystique.png', pdf:'assets/pdfs/villain-mystique.pdf' },
    juggernaut: { image:'assets/portraits/villain-juggernaut.png', pdf:'assets/pdfs/villain-juggernaut.pdf' },
    magneto: { image:'assets/portraits/villain-magneto.png', pdf:'assets/pdfs/villain-magneto.pdf' },
    annihilus: { image:'assets/portraits/villain-annihilus.png', pdf:'assets/pdfs/villain-annihilus.pdf' },
    'super-skrull': { image:'assets/portraits/villain-super-skrull.png', pdf:'assets/pdfs/villain-super-skrull.pdf' },
    blastaar: { image:'assets/portraits/villain-blastaar.png', pdf:'assets/pdfs/villain-blastaar.pdf' },
    'molecule-man': { image:'assets/portraits/villain-molecule-man.png', pdf:'assets/pdfs/villain-molecule-man.pdf' },
    kingpin: { image:'assets/portraits/villain-kingpin.png', pdf:'assets/pdfs/villain-kingpin.pdf' },
    bullseye: { image:'assets/portraits/villain-bullseye.png', pdf:'assets/pdfs/villain-bullseye.pdf' },
    ajax: { image:'assets/portraits/villain-ajax.png', pdf:'assets/pdfs/villain-ajax.pdf' },
    tombstone: { image:'assets/portraits/villain-tombstone.png', pdf:'assets/pdfs/villain-tombstone.pdf' },
    madcap: { image:'assets/portraits/villain-madcap.png', pdf:'assets/pdfs/villain-madcap.pdf' },
    't-ray': { image:'assets/portraits/villain-t-ray.png', pdf:'assets/pdfs/villain-t-ray.pdf' },
    elektra: { image:'assets/portraits/villain-elektra.png', pdf:'assets/pdfs/villain-elektra.pdf' }
  }
};
Object.entries(CHARACTER_ASSETS.heroes).forEach(([id,asset])=>{ if(CHARACTER_LIBRARY.heroes[id]) Object.assign(CHARACTER_LIBRARY.heroes[id], asset); });
Object.entries(CHARACTER_ASSETS.villains).forEach(([id,asset])=>{ if(CHARACTER_LIBRARY.villains[id]) Object.assign(CHARACTER_LIBRARY.villains[id], asset); });

const TEMPLATE_PDFS = {
  arachne:'assets/pdfs/campanha-projeto-arachne.pdf',
  'avengers-doom':'assets/pdfs/campanha-vingadores-protocolo-destino.pdf',
  'xmen-apocalypse':'assets/pdfs/campanha-xmen-era-do-apocalipse.pdf',
  'fantastic-negative-zone':'assets/pdfs/campanha-quarteto-zona-negativa.pdf',
  'hells-kitchen-nightfall':'assets/pdfs/campanha-sombras-de-hells-kitchen.pdf'
};

function characterList(kind){
  if(kind==='hero') return Object.values(CHARACTER_LIBRARY.heroes).map(clone);
  if(kind==='villain') return Object.values(CHARACTER_LIBRARY.villains).map(clone);
  return { heroes: characterList('hero'), villains: characterList('villain') };
}
function getChar(kind,id){ const bucket = kind==='hero' ? CHARACTER_LIBRARY.heroes : CHARACTER_LIBRARY.villains; return bucket[id] ? clone(bucket[id]) : null; }
function buildScenarioPieces(heroes){
  return heroes.slice(0,6).map((h,i)=>({id:`hero-${h.id}`,kind:'hero',baseId:h.id,name:h.n,short:h.n.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase(),color:['#ef4444','#facc15','#3b82f6','#22c55e','#a855f7','#06b6d4'][i%6],x:2+i*2,y:12,movement:h.movement||{run:5,climb:3,swim:3,jump:3}}));
}
function buildTemplate({id,name,subtitle,rank,players,finalVillain,accent,summary,source='uploaded-campaign',campaignPdf='',heroIds=[],villainIds=[],sessions=[]}){
  return { id,name,subtitle,rank,players,finalVillain,accent,summary,source,campaignPdf, heroes: heroIds.map(heroId=>getChar('hero',heroId)).filter(Boolean), villains: villainIds.map(villainId=>getChar('villain',villainId)).filter(Boolean), sessions };
}

const templates = [
  buildTemplate({
    id:'arachne', name:'Projeto Arachne', subtitle:'Conspiração genética em 8 sessões', rank:4, players:3, finalVillain:'Senhor Sinistro', accent:'#ef3340', source:'built-in', campaignPdf:'assets/pdfs/campanha-projeto-arachne.pdf',
    summary:'Três heróis investigam roubos científicos, laboratórios clandestinos e coleta genética que converge para o Projeto Arachne de Nathaniel Essex.',
    heroIds:['spider','wolverine','cap'], villainIds:['octopus','sabretooth','crossbones','goblin','sinister','hydra-agent','aim-agent'],
    sessions:[
      session(1,'O Roubo','Os heróis investigam roubos diferentes e chegam ao mesmo laboratório. A pista aponta para Otto Octavius.'),
      session(2,'Doutor Octopus','Otto transporta uma amostra crítica. Documentos apontam para Essex.'),
      session(3,'O Caçador','Dentes-de-Sabre entra em cena e força Logan a encarar a caçada genética.'),
      session(4,'Hydra','Crossbones e agentes Hydra atacam uma instalação para roubar as amostras.'),
      session(5,'Duende Verde','Norman Osborn invade o projeto e revela que existe outra facção interessada.'),
      session(6,'Essex','Os heróis descobrem Nathaniel Essex e a arquitetura do plano maior.'),
      session(7,'Madripoor','A equipe segue a trilha até o laboratório final e encontra novos obstáculos.'),
      session(8,'Projeto Arachne','Senhor Sinistro revela o objetivo da pesquisa. Combate final com o laboratório entrando em colapso.')
    ]
  }),
  buildTemplate({
    id:'avengers-doom', name:'Os Vingadores — Protocolo Destino', subtitle:'Controle vs. escolha', rank:4, players:3, finalVillain:'Doutor Destino', accent:'#d72b39', campaignPdf:'',
    summary:'Doom coleta tecnologia, energia asgardiana e padrões de decisão para construir a Matriz Destino, capaz de impor uma única realidade sobre futuros possíveis.',
    heroIds:['iron-man','cap','thor'], villainIds:['doom','loki','zemo','abomination','enchantress'],
    sessions:[
      session(1,'O Ataque ao Núcleo Stark','Mercenários atacam um reator experimental e coletam uma assinatura energética crítica.'),
      session(2,'Loki — Chave Asgardiana','Um artefato asgardiano desaparece e Loki desvia a atenção do grupo.'),
      session(3,'O Barão Zemo','Zemo coleta padrões táticos e a assinatura do escudo de Steve Rogers.'),
      session(4,'O Abominável','Blonsky serve como teste vivo para a capacidade de carga da Matriz.'),
      session(5,'A Encantadora','Amora desbloqueia a chave asgardiana e revela o objetivo de Doom.'),
      session(6,'Latvéria','Os Vingadores chegam a Latvéria e encaram a ativação parcial da Matriz.'),
      session(7,'A Guerra de Doom','Portais surgem e o grupo precisa escolher quais objetivos consegue resolver.'),
      session(8,'Protocolo Destino','Doom ativa a Matriz. A vitória depende de quebrar suas três dependências centrais.')
    ]
  }),
  buildTemplate({
    id:'xmen-apocalypse', name:'X-Men — Era do Apocalipse', subtitle:'Projeto Evolução', rank:4, players:5, finalVillain:'Apocalypse', accent:'#e7cf31', campaignPdf:'',
    summary:'Desaparecimentos mutantes, falsas bandeiras e experimentos genéticos alimentam o Catalisador de Akkaba, criado para forçar evolução em escala global.',
    heroIds:['wolverine','cyclops','storm','iceman','gambit'], villainIds:['apocalypse','sinister','mystique','sabretooth','juggernaut','magneto'],
    sessions:[
      session(1,'Os Desaparecidos','Os X-Men encontram um armazém da Essex Genetics e descobrem o Projeto Evolução.'),
      session(2,'Dentes-de-Sabre','Victor Creed caça amostras de mutantes resistentes e coloca Logan no centro do experimento.'),
      session(3,'Sr. Sinistro','Os arquivos revelam as funções técnicas do plano e a ligação com Akkaba.'),
      session(4,'Magneto','Magneto protege mutantes enquanto Mística rouba a Chave de Akkaba.'),
      session(5,'O Juggernaut','Cain Marko transporta o Núcleo do Catalisador; impedir sua chegada vira prioridade.'),
      session(6,'Os Quatro Cavaleiros','Apocalypse inicia conversões e o banco genético chega a 92%.'),
      session(7,'A Guerra','Falsas ordens e ataques empurram humanos e mutantes para um conflito global.'),
      session(8,'Era do Apocalipse','Em Akkaba, os heróis descobrem que toda a campanha foi parte da calibração do Catalisador.')
    ]
  }),
  buildTemplate({
    id:'fantastic-negative-zone', name:'Quarteto Fantástico — A Zona Negativa', subtitle:'Ciência, família e invasão dimensional', rank:4, players:4, finalVillain:'Annihilus', accent:'#21a8e5', campaignPdf:'',
    summary:'A assinatura do Portal Baxter atrai Annihilus, que constrói uma ponte permanente entre universos enquanto Doom tenta transformar a crise em fonte de poder.',
    heroIds:['mr-fantastic','invisible-woman','human-torch','thing'], villainIds:['annihilus','doom','super-skrull','blastaar','molecule-man'],
    sessions:[
      session(1,'O Sinal','O Portal Baxter sincroniza com uma frequência externa e criaturas atravessam a barreira.'),
      session(2,'Doom','Doom rouba um fragmento do acoplador dimensional para construir o próprio coletor.'),
      session(3,'O Super-Skrull','Kl’rt cai na Terra com um mapa subespacial roubado da Onda de Aniquilação.'),
      session(4,'Matéria em Colapso','A instabilidade dimensional ressoa com Owen Reece, que se torna pista viva da crise.'),
      session(5,'A Zona Negativa','O Quarteto atravessa o portal, encontra refugiados e decide como lidar com Blastaar.'),
      session(6,'O Senhor da Zona Negativa','Annihilus revela o Motor de Ancoragem e os quatro condutores de fase.'),
      session(7,'O Acordo de Doom','Doom oferece controlar o colapso em troca da energia dimensional.'),
      session(8,'A Onda de Aniquilação','A ponte abre e a batalha final exige quatro tarefas simultâneas e uma escolha difícil.')
    ]
  }),
  buildTemplate({
    id:'hells-kitchen-nightfall', name:"Sombras de Hell's Kitchen", subtitle:'Nightfall está observando', rank:4, players:4, finalVillain:'Wilson Fisk', accent:'#e9303f', campaignPdf:'',
    summary:'Uma droga de rua e uma onda de violência alimentam Nightfall, sistema de Fisk que transforma cada confronto em dados para prever e neutralizar vigilantes.',
    heroIds:['daredevil','luke-cage','spider','deadpool'], villainIds:['kingpin','bullseye','ajax','tombstone','madcap','t-ray','elektra'],
    sessions:[
      session(1,'A Droga Nitro-X','Os heróis convergem para o mesmo prédio, onde Fisk coleta telemetria através de um incidente deliberado.'),
      session(2,'Bullseye','Bullseye elimina testemunhas e mede a reação do Demolidor.'),
      session(3,'Ajax','Ajax estabiliza usuários da Nitro-X e coleta dados biológicos para Fisk.'),
      session(4,'Tombstone','A violência de rua se conecta ao plano imobiliário da Fisk Urban Development.'),
      session(5,'Madcap','Um lote instável rompe o experimento controlado e expõe a cadeia de suprimentos.'),
      session(6,'T-Ray','O arquivo negro revela que todas as lutas anteriores treinaram Nightfall.'),
      session(7,'O Rei do Crime','Fisk organiza o último teste controlado antes da ativação.'),
      session(8,'Nightfall','Hell’s Kitchen entra em lockdown e os heróis precisam derrotar Fisk, quebrar Nightfall e escolher o que salvar.')
    ]
  })
];

function rosterSummary(items, kind='hero'){
  return items.map(item => kind==='hero'
    ? { id:item.id,n:item.n,r:item.r,rank:item.rank,image:item.image||'',pdf:!!item.pdf,role:item.role||'',powers:item.powers||[],abilities:item.abilities||baseAbilities }
    : { id:item.id,n:item.n,r:item.r,rank:item.rank,tier:item.tier,image:item.image||'',pdf:!!item.pdf,role:item.role||'',powers:item.powers||[],abilities:item.abilities||baseAbilities }
  );
}

templates.forEach(template=>{ if(TEMPLATE_PDFS[template.id]) template.campaignPdf = TEMPLATE_PDFS[template.id]; });

export function publicTemplate(template){
  return {
    id:template.id,name:template.name,subtitle:template.subtitle,rank:template.rank,players:template.players,finalVillain:template.finalVillain,accent:template.accent,summary:template.summary,source:template.source,campaignPdf:template.campaignPdf||'',
    heroes:rosterSummary(template.heroes,'hero'),
    villains:rosterSummary(template.villains,'villain'),
    sessions:template.sessions.map(s=>({id:s.id,title:s.title,text:s.text}))
  };
}
export function getTemplates(){ return templates.map(clone); }
export function getTemplate(id){ const found = templates.find(t=>t.id===id); return found ? clone(found) : null; }
export function getCharacterLibrary(kind='all'){ return characterList(kind); }
export function getCharacter(kind,id){ return getChar(kind,id); }
export function applyRoster(seed,{heroIds=[],villainIds=[]}={}){
  const next = clone(seed || blankSeed('Nova Campanha'));
  if(Array.isArray(heroIds)) next.heroes = [...new Set(heroIds)].map(id=>getChar('hero',id)).filter(Boolean);
  if(Array.isArray(villainIds)) next.villains = [...new Set(villainIds)].map(id=>getChar('villain',id)).filter(Boolean);
  next.playerNotes = Object.fromEntries((next.heroes||[]).map(hero=>[hero.id, next.playerNotes?.[hero.id] || '']));
  next.campaignContent = { ...(next.campaignContent||{}), players:(next.heroes||[]).length };
  const boss = (next.villains||[]).find(v=>v.tier==='CHEFE FINAL') || next.villains?.[0] || null;
  if(boss) next.campaignContent.finalVillain = boss.n;
  if(next.challenge) next.challenge.actor = next.heroes?.[0]?.id || '';
  if(next.scenario) next.scenario.pieces = buildScenarioPieces(next.heroes||[]);
  return next;
}
export function templateSeed(id){
  const t=getTemplate(id); if(!t) return null;
  return {
    heroes: clone(t.heroes),
    villains: clone(t.villains),
    campaign: Object.fromEntries(t.sessions.map(s=>[s.id,'todo'])),
    campaignContent:{ title:t.name, subtitle:t.subtitle, summary:t.summary, rank:t.rank, players:t.players, finalVillain:t.finalVillain, accent:t.accent, sessions:clone(t.sessions), documentMode:t.campaignPdf?'pdf':'editor', campaignPdf:t.campaignPdf||'', editorText:t.summary, templateId:t.id, templateName:t.name },
    dice:[], challenge:{ action:'Ação sem título', tn:14, edge:0, trouble:0, source:'hero', actor:t.heroes[0]?.id||'', threatTier:'minion', threatChoice:'minion-melee', ability:'Agility', extra:0 },
    scenario:{ preset:'empty', environment:'lab', width:20, height:14, baseTerrain:'floor', selectedTool:'select', selectedPiece:null, selectedMode:'run', zoom:1, obstacles:{}, terrain:{}, decor:{}, turnMovement:{}, movementSpent:{}, pieces:buildScenarioPieces(t.heroes) },
    initiative:[], playerNotes:Object.fromEntries(t.heroes.map(h=>[h.id,''])), notesMaster:''
  };
}
export function blankSeed(name='Nova Campanha'){
  return {
    heroes:[], villains:[], campaign:{},
    campaignContent:{ title:name, subtitle:'Campanha personalizada', summary:'', rank:4, players:0, finalVillain:'', accent:'#ef3340', sessions:[], documentMode:'editor', campaignPdf:'', editorText:'', templateId:'blank', templateName:'Em branco' },
    dice:[], challenge:{ action:'Ação sem título', tn:14, edge:0, trouble:0, source:'hero', actor:'', threatTier:'minion', threatChoice:'minion-melee', ability:'Agility', extra:0 },
    scenario:{ preset:'empty', environment:'lab', width:20, height:14, baseTerrain:'floor', selectedTool:'select', selectedPiece:null, selectedMode:'run', zoom:1, obstacles:{}, terrain:{}, decor:{}, turnMovement:{}, movementSpent:{}, pieces:[] },
    initiative:[], playerNotes:{}, notesMaster:''
  };
}
